### ISSUE TITLE
Account.ID is int but accountID arguments are a string

### ISSUE THREAD

**Issue by fastest963** [aetrion/dnsimple-go#22]
`Account.ID` is an `int` but `ListDomains(accountID string, options *ListOptions)` accepts a string. Can you just make `Account.ID` be a string or make `ListDomains` accept an `int`?

**Comment by weppos** [comment]
Thanks for the feedback. There is actually a reason behind this decision.

The Account.ID you get as part of the `Account` struct is an incremental integer. However, when you will pass the account identifier as `accountID` parameter, you will be able to use both the incremental ID or the string identifier of the account (e.g. `1234` vs `weppos`).

Nowadays passing the identifier is not supported yet, but it will in the near future. Therefore we are passing it as a string otherwise in the future it will be an issue when passing the identifier as `accountID` will be supported.

**Comment by weppos** [comment]
Closing because of the explanation above. Feel free to follow up if you need more info.
